name: Purge README
on: 
    push:
    schedule:
        - cron: '0 0 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/purge-readme@v1
        with:
          repo: Patchwork-Archive/.github
          branch: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          paths: |
            README.md