name: Purge Camo Images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  purge_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run shell script
        run: |
          chmod +x camo-purge.sh
          ./camo-purge.sh ${{ github.repository }}
